
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

# Site settings
title: TronGov
subtitle: "The end-to-end government enablement and prototype accelerator"
url: "https://trongov.us" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
# cover: "/assets/cover.png"
# logo: "/assets/logo.png"

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# # Category descriptions (for archive pages)
# descriptions:
#   - cat: jekyll
#     desc: "Posts describing Jekyll setup techniques."

#   - cat: dummy
#     desc: "Just some placeholder posts, lorem ipsum and the rest."
